version: '3'

services:
  react-vite-app:
    container_name: bctm_fe_cmu
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped